FROM python:3.9-slim

WORKDIR /app

# Install required Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your mock filing service app code
COPY filing_service.py .

EXPOSE 5001

CMD ["python", "filing_service.py"]